### ISSUE TITLE
No image processing?

### ISSUE THREAD

**Issue by edoardobiasini** [locomotivemtl/locomotive-boilerplate#115]
I can't seem to find any reference in build.js or watch.js
What is the purpose of having an `images` folder inside above root `assets` folder if those images don't get copied/optimized inside the `assets` folder available under `www`?

**Comment by Jerek0** [comment]
Hi, we currently only use the images folder to generate an SVG sprite based on SVG files you put in `assets/images/sprite` or as specified in loconfig.json
