### ISSUE TITLE
Kept buffering

### ISSUE THREAD

**Issue by byalexlynpi** [locomotivemtl/locomotive-boilerplate#145]
npm start opens up a browser window but kept on spinning

**Comment by devenini** [comment]
Hey! Your `loconfig.json` should contain a `paths.url` (check out the [documentation](https://github.com/locomotivemtl/locomotive-boilerplate/blob/master/docs/development.md#pathsurl-option)) with the domain name you're using for local development. Have you set up a virtual host that points to the `your-project/www/` directory?

**Comment by devenini** [comment]
Alternatively you have the option to remove the `paths.url` line from your project configuration (reference [here](https://github.com/locomotivemtl/locomotive-boilerplate/blob/3fee6f48880122fe66baba5749b2ba707ee47962/loconfig.json#L3)). By doing so, the default proxy URL will be set to `localhost:3000`.
