### ISSUE TITLE
npm build will not build css if www/css folder deson't exit

### ISSUE THREAD

**Issue by islam-hamza** [locomotivemtl/locomotive-boilerplate#158]
I understand that www is just a placeholder
if that folder doesn't exist the build process will fail to generate styles
with the following error:

`Error: ENOENT: no such file or directory, open './www/assets/styles/main.css'`

it generates js files without issues but it failed to build the styles
any possible fixes ?

**Comment by devenini** [comment]
Hey! Good catch, I was able to reproduce the issue when I deleted the `./www` folder. For now we don't have a fix. You can either create the directories `./www/assets/styles/` or change the styles `"dest"` path in your `loconfig.json`.

**Comment by devenini** [comment]
Fixed
