### ISSUE TITLE
Comments Syntax: /* */ and //

### ISSUE THREAD

**Issue by mcaskill** [locomotivemtl/locomotive-boilerplate#25]
> Sass supports standard multiline CSS comments with `/* ... */`, as well as single-line comments with `// ...`. The multiline comments are preserved in the CSS output where possible, while the single-line comments are removed.
— [Sass Reference](http://sass-lang.com/documentation/file.SASS_REFERENCE.html#comments)

When documenting styles that don't output CSS on their own (_placeholder selectors_, _functions_, and _mixins_), we should use the single-line syntax to avoid outputting unnecessary comments for a CSS-environment.

This is a syntax issue I see often in our projects this past year; see [_tools.scss](/locomotivemtl/locomotive-boilerplate/www/modules/boilerplate/assets/styles/src/tools/_tools.scss) for an example.

This is a moot point when minifying CSS and stripping out all comments, I just think it's a good practice to consider.

Also: [SassDoc](http://sassdoc.com/annotations/) should be used as an example of how to structure Sass documentation.

**Comment by AntoineBoulanger** [comment]
Indeed, live sites are minified so it doesn't matter but why not when dev.
When I have time, or if anyone has, we can change these:
```
/* ==========================================================================
   Heading comment
   ========================================================================== */

/* Sub comment
   ========================================================================== */
```

For:

```
// ==========================================================================
// Heading comment
// ==========================================================================

// Sub comment
// ==========================================================================
```

I'll share my sublime snippets if you want to.

**Comment by stephenbe** [comment]
https://github.com/locomotivemtl/locomotive-boilerplate/pull/26
