### ISSUE TITLE
Remove the Charcoal part of the locomotive-boilerplate

### ISSUE THREAD

**Issue by AntoineBoulanger** [locomotivemtl/locomotive-boilerplate#37]
When Charcoal 2.0 is ready to use and we won't start projects with Charcoal Legacy anymore, it would be nice to remove everything Charcoal related from this boilerplate and use 
https://github.com/locomotivemtl/charcoal-project-boilerplate 
for this. 

We often build static or WordPress sites and it's better being modular than putting everything in one and removing stuff every time. 

So if you build a Charcoal website, you start with the charcoal-project-boilerplate, add in the grunt tasks, scss, js... from locomotive-boilerplate and you are good to go, otherwise you just start from here.

**Comment by mcaskill** [comment]
The structure wouldn't match with the Charcoal Neue to mix with WordPress or Legacy.

```
locomotive.ca/
├── assets/
│   └── locomotive/
│       └── Raw assets (LESS, Sass, CoffeeScript, etc.)
├── config/
├── metadata/
├── src/
├── templates/
│   └── locomotive/
│       └── ...
├── vendor/
└── www/
    └── assets/
        └── locomotive/
            └── Compiled assets (JavaScript, CSS, etc.)
```

**Comment by dominiclord** [comment]
Fixed in https://github.com/locomotivemtl/locomotive-boilerplate/pull/39
