### ISSUE TITLE
Page 404 on gulp

### ISSUE THREAD

**Issue by ystroobants** [locomotivemtl/locomotive-boilerplate#67]
Hello

When I make a gulp browsersync opens a new window but with a 404 error.

**Run**
[Browsersync] Proxying: http://boilerplate.test
[Browsersync] Access URLs:
 -----------------------------------------
       Local: http://localhost:3004
    External: http://boilerplate.test:3004
 -----------------------------------------
          UI: http://localhost:3005
 UI External: http://localhost:3005
 -----------------------------------------

Error Msg: Safari can not find the server boilerplate test
I checked if Mac OSX firewall is up and running but it's disabled.

Can you help me please?
Thanks

**Comment by antoineboulanger** [comment]
If you want to use http://boilerplate.test, you have to add it to your hosts file. Try localhost.

**Comment by ystroobants** [comment]
Thanks for your quick reply. so i have to modify host:paths.url in serve.js with host:localhost?
