### ISSUE TITLE
Error: Cannot find module './build/styles.js'

### ISSUE THREAD

**Issue by ronca85** [locomotivemtl/locomotive-boilerplate#69]
howdy, fellas. i was trying out your boilerplate but i had trouble setting it up. this is the error message i got when running gulp:

Error: Cannot find module './build/styles.js'

there's more files that are missing in the build folder so i'd like to know what's up with that.

thanks.

**Comment by antoineboulanger** [comment]
You probably didn't do `mbp init`

**Comment by ronca85** [comment]
@antoineboulanger hello,

i found all that was missing in locomotive-scroll repo.

thanks.

**Comment by shahasnizar** [comment]
@ronca85 hello,

how you resolved this error..pls help

thanks.

**Comment by ronca85** [comment]
@shahasnizar i was setting up charcoal https://github.com/locomotivemtl/charcoal-project-boilerplate
this repo provides some dependencies that are missing in frontend-boilerplate. here's the package.json that gets generated when setting up charcoal. compare and add missing dependencies from this file to the one you have
[package.json.txt](https://github.com/locomotivemtl/locomotive-boilerplate/files/5287242/package.json.txt)

**Comment by antoineboulanger** [comment]
You don't have to edit the package.json. Just run `mbp init` in your terminal. You need it installed first `npm install mbp -g`.
