### ISSUE TITLE
Making all grunt tasks external

### ISSUE THREAD

**Issue by stephenbe** [locomotivemtl/locomotive-boilerplate#7]
Hello,

I was wondering what you guys thought if we made all the grunt tasks external instead of having a few internal and external. I think it would make searching and modifying grunt tasks easier!

Tell me what you think.

Stephen

**Comment by AntoineBoulanger** [comment]
I approve! I only made the tasks that I was often editing and needed to refresh on watch external, to not change everything, but i'm ready for everything external. 

Much cleaner and easier to maintain, instead of scrolling to find what you want, just: `ctrl + p`.

**Comment by dominiclord** [comment]
:thumbs_up:

**Comment by stephenbe** [comment]
44356da29a3a8ad53b3cab19a79e8dc60ebcf0d9
