### ISSUE TITLE
Can't Access http://localhost:3000/

### ISSUE THREAD

**Issue by sibaturaspirman** [locomotivemtl/locomotive-boilerplate#71]
i try use this boilerplate but i can't access http://localhost:3000/ or http://boilerplate.test:3000/ just loading...

![image](https://user-images.githubusercontent.com/14294482/67746102-5adcda00-fa58-11e9-9eb4-f1e8b2a7fbb6.png)

**Comment by spagnolodesign** [comment]
Same here, have you guys checked on this?

**Comment by antoineboulanger** [comment]
Hi, for our setup, we use a proxy server to run `boilerplate.test`. 
To just run the boilerplate from `localhost:3000`, you'll have to edit the `build/serve.js` file.
You can just replace the content of the file with this:
```js
import browserSync from 'browser-sync';
import paths from '../mconfig.json';

export const server = browserSync.create();

function serve(done) {
    server.init({
        notify: false,
        server: {
            baseDir: paths.dest
        }
    });
    done();
}

export default serve;
```
I haven't found a way to make both ways work out of the box yet.

**Comment by itsanan** [comment]
Hi @antoineboulanger i haven't able to open both **_localhost:3000_** or **_boilerplate.test:3000_** it just stuck loading, any help would be appreciate 🙏🏻

<img width="845" alt="Screenshot 2020-08-08 at 8 33 37 PM" src="https://user-images.githubusercontent.com/32235492/89711824-ddff6900-d9b6-11ea-9c83-4a4e0942bb26.png">

<img width="675" alt="Screenshot 2020-08-08 at 8 38 31 PM" src="https://user-images.githubusercontent.com/32235492/89711891-5108df80-d9b7-11ea-8e29-74d1db273e75.png">

**Comment by Khwarazmi** [comment]
Has anyone found a solution ? there is no serve file anymore after the last update

**Comment by indaviande** [comment]
Same here,  I got this message when doing `npm start`
``` ~/locomotive-boilerplate-master/node_modules/esbuild/lib/main.js:236:12: error: Invalid option in build() call: "errorLimit"
    236 │       throw new Error(`Invalid option ${where}: "${key}"`); ```

**Comment by manuelruizredondo** [comment]
Doesn't work, localhost is loading, serve.js no exist.

**Comment by MouseEatsCat** [comment]
There are 2 possible solutions for this that seem to work for me:

1. Add `boilerplate.test` to your hosts file (or any domain you wish to use). You can change the `"url"` value in the project's `./mconfig.json` file. You can then set up a virtualhost that uses `./www` as it's document root. ([virtualhost examples](https://httpd.apache.org/docs/2.4/vhosts/examples.html))
2. A quicker solution would be to modify `./build/watch.js`. On line 11, you can modify the `bs.init` segment to look like this:
```javascript
// Start the Browsersync server
bs.init({
    //proxy: paths.url,
    server: {
        baseDir: paths.dest
    },
    open: false,
    notify: false
});
```
