### ISSUE TITLE
Default Layout Broken

### ISSUE THREAD

**Issue by pedrocardoz0** [locomotivemtl/locomotive-boilerplate#77]
Somehow the default layout is broken to me.

![Screen Shot 2021-02-13 at 10 59 03](https://user-images.githubusercontent.com/24881317/107851676-7ead6600-6dea-11eb-81fb-974df92283ae.png)

**Comment by mcaskill** [comment]
The HTML files in the `www` directory is, at the of writing, more of a placeholder than a practical example.
