### ISSUE TITLE
Editing html and views folder

### ISSUE THREAD

**Issue by one618** [locomotivemtl/locomotive-boilerplate#78]
Hello,

Am I supposed to edit the html files directly from www folder ? and what is the purpose of the views folder ?
I know this question is coming from my lack of knowledge and experience I do apologize

thank you in advance

**Comment by mcaskill** [comment]
In most of our projects, we use a templating engine like Mustache or Twig and we store the template files in the `views` directory. These templates are dynamically served from a server-side controller like PHP or compiled into HTML files in the `www` directory.

The `./views/boilerplate/template` value in the ~`mconfig.json`~ `loconfig.json` can be changed to point to wherever you store your templates (be they HTML or a template engine files).

The primary focus of this boilerplate are the `assets` and `build` directories.
