### ISSUE TITLE
Any plans to ditch Sass for PostCSS?

### ISSUE THREAD

**Issue by elliottmangham** [locomotivemtl/locomotive-boilerplate#89]
Hey!

Just curious really, I wondered why you choose Sass over [PostCSS](https://github.com/postcss/postcss), and if you have any plans to migrate to the latter?

Best,

**Comment by devenini** [comment]
Hello! We understand the benefits of using PostCSS, but at this time, we do not have plans to fully transition away from Sass in the near future.
